name: Basic Workflow with Variables

on:
  push:
    branches: [ "main" ]  # Runs on push to main branch
  workflow_dispatch:       # Allows manual trigger

env:
  WORKFLOW_LEVEL_VAR: "This is a workflow-level variable"  # Workflow-level variable
  Var: "Hi From Workflow" 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_VAR: "This is a job-level variable"  # Job-level variable
      Var: "Hi From Job"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Step Level Variable
        env:
          STEP_LEVEL_VAR: "This is a step-level variable"  # Step-level variable
          Var: "Hi From Step"
        run: |
          echo "Workflow Variable: $WORKFLOW_LEVEL_VAR"
          echo "Job Variable: $JOB_LEVEL_VAR"
          echo "Step Variable: $STEP_LEVEL_VAR"
          echo "Var : $Var"

      - name: Print GitHub Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      JOB_LEVEL_DEPLOY_VAR: "Deploying application"

    steps:
      - name: Deploy Step
        env:
          STEP_LEVEL_DEPLOY_VAR: "Step-level deployment variable"
        run: |
          echo "Workflow Variable: $WORKFLOW_LEVEL_VAR"
          echo "Job Variable: $JOB_LEVEL_DEPLOY_VAR"
          echo "Step Variable: $STEP_LEVEL_DEPLOY_VAR"
