name: Secrets

on: 
  workflow_dispatch:        # Allows manual trigger

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Use Secret
        run: echo "My secret value is ${{ secrets.MY_SECRET }}"
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}

      - name: Print Secret (Base64 Encoded)
        run: echo $SECRET_VALUE | base64
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}

      #- name: Intentional Failure
      #run: exit 1 

      - name: Simulate Task Success
        run: echo "This task was successful!"

      - name: Success Message
        if: ${{ success() }}
        run: echo "Previous job was successful!"

      - name: Failure Message
        if: ${{ failure() }}
        run: echo "Previous job failed!"

      - name: Always Execute
        if: ${{ always() }}
        run: echo "This step always runs."

 
